// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/childelins/go-skeleton/app/http/controller/api/v1"
	"github.com/childelins/go-skeleton/app/repository"
	"github.com/childelins/go-skeleton/app/service"
	"github.com/childelins/go-skeleton/bootstrap"
	"github.com/childelins/go-skeleton/pkg/container"
	"gorm.io/gorm"
)

import (
	_ "github.com/childelins/go-skeleton/config"
)

// Injectors from wire.go:

func BuildApp(db *gorm.DB) *bootstrap.App {
	healthController := v1.NewHealthController()
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userController := v1.NewUserController(userService)
	containerContainer := container.New(healthController, userController)
	app := bootstrap.NewApp(containerContainer)
	return app
}
